name: Deploy To Server

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST -d "token=${{secrets.GITHUB_TOKEN}}" -H "Authorization=${{secrets.SERVER_AUTHORIZATION}}" ${{secrets.SERVER_URL}}